CREATE TABLE estudiante(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cedula INTEGER NOT NULL,carne INTEGER NOT NULL,pin VARCHAR2(100) NOT NULL,
    nombre VARCHAR2(100) NOT NULL,primer_apellido VARCHAR2(100) NOT NULL,
    segundo_apellido VARCHAR2(100) NOT NULL,correo VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(100) NOT NULL,telefono INTEGER NOT NULL,PRIMARY KEY (id));


CREATE TABLE sede(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(100) NOT NULL,
    PRIMARY KEY (id));


CREATE TABLE profesor(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cedula INTEGER NOT NULL,nombre VARCHAR2(100) NOT NULL,
    primer_apellido VARCHAR2(100) NOT NULL,segundo_apellido VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL,direccion VARCHAR2(100) NOT NULL,
    telefono INTEGER NOT NULL, id_sede INTEGER NOT NULL,FOREIGN KEY (id_sede) REFERENCES sede(id),
    PRIMARY KEY (id));

CREATE TABLE curso(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    codigo VARCHAR2(100) NULL,nombre VARCHAR2(100) NOT NULL,
    cupos INTEGER NOT NULL, grupo VARCHAR2(100) NOT NULL,
    horario VARCHAR2(100) NOT NULL, id_sede INTEGER NOT NULL,
    id_profesor INTEGER NOT NULL,FOREIGN KEY (id_sede) REFERENCES sede(id),
    FOREIGN KEY (id_profesor) REFERENCES profesor(id), PRIMARY KEY (id));

CREATE TABLE historial(

                          id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          operacion VARCHAR(100) NOT NULL,
                          usuario VARCHAR(100) NOT NULL,
                          nombre_tabla VARCHAR(100),
                          id_tabla NUMBER,
                          datos_anteriores VARCHAR(1000),
                          datos_nuevos VARCHAR(1000),

                          PRIMARY KEY (id)
);